version: "3.1"
services:
  express-mongo:
    build: .
    command: "npm run prod"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - net-app

  mongo:
    image: mongo
    container_name: mongo-app
    volumes:
        - .docker-volumes/mongo:/data/db
    restart: always
    networks:
      - net-app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - net-app

networks:
   net-app:
     driver: bridge